// Generated by tools/build-stock-vehicle-catalog.py. Do not edit by hand.

import { NSDF_STOCK_VEHICLES } from './stock-vehicles.nsdf.generated';
import { BLACK_DOG_STOCK_VEHICLES } from './stock-vehicles.black-dog.generated';
import { CCA_STOCK_VEHICLES } from './stock-vehicles.cca.generated';
import { CRA_STOCK_VEHICLES } from './stock-vehicles.cra.generated';

export const GENERATED_STOCK_VEHICLES = Object.freeze({
    ...NSDF_STOCK_VEHICLES,
    ...BLACK_DOG_STOCK_VEHICLES,
    ...CCA_STOCK_VEHICLES,
    ...CRA_STOCK_VEHICLES
});
