// Generated by Web/tools/generate-vehicle-images.mjs. Do not edit by hand.

export interface StockVehicleImageDefinition {
    thumbnailUrl: string;
    sourceUrl: string | null;
}

export const GENERATED_STOCK_VEHICLE_IMAGES: Readonly<Record<string, StockVehicleImageDefinition>> =
    Object.freeze({});
