// Generated by tools/build-stock-vehicle-catalog.py. Do not edit by hand.

import type { StockFactionKey, StockVehicleDefinition } from './stock-vehicles';
import { STOCK_VEHICLE_ROWS_01 } from './stock-vehicles.rows-01.generated';
import { STOCK_VEHICLE_ROWS_02 } from './stock-vehicles.rows-02.generated';
import { STOCK_VEHICLE_ROWS_03 } from './stock-vehicles.rows-03.generated';
import { STOCK_VEHICLE_ROWS_04 } from './stock-vehicles.rows-04.generated';

type StockVehicleWeaponRow = readonly [number, string | null, string | null];
type StockVehicleRow = readonly [
    string, string, StockFactionKey | null, string | null, string | null,
    number | null, number | null, number | null, number | null, number | null,
    string | null, string | null, number | null, number | null, number | null,
    string | null, string | null, string | null, readonly StockVehicleWeaponRow[]
];

const rows: readonly StockVehicleRow[] = [
    ...STOCK_VEHICLE_ROWS_01,
    ...STOCK_VEHICLE_ROWS_02,
    ...STOCK_VEHICLE_ROWS_03,
    ...STOCK_VEHICLE_ROWS_04
];

export const GENERATED_STOCK_VEHICLES: Readonly<Record<string, StockVehicleDefinition>> =
    Object.freeze(Object.fromEntries(rows.map(row => [row[0], {
        code: row[0],
        unitName: row[1],
        faction: row[2],
        baseName: row[3],
        classLabel: row[4],
        scrapValue: row[5],
        scrapCost: row[6],
        buildTime: row[7],
        maxHealth: row[8],
        maxAmmo: row[9],
        aiName: row[10],
        aiName2: row[11],
        heatSignature: row[12],
        imageSignature: row[13],
        radarSignature: row[14],
        weaponMask: row[15],
        thumbnailUrl: row[16],
        thumbnailSourceUrl: row[17],
        weapons: row[18].map(weapon => ({ slot: weapon[0], hardpoint: weapon[1], odf: weapon[2] }))
    }])));
